/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
function displayArray (n){
  var arr = [];
  var arr2 = [];
  for (var i = 1; i < n+1; i++){
    arr.push(fib(i));
  }
  for (var j = 0; j < arr.length; j++){
    if (arr[j]%2===0){
      arr2.push(arr[j]);
    }
  }
  return arr2.reduce(add);
}

function fib(num){
  if (num===0|num==1|num==2){
    return num;
  }
  else{
    return this.fib(num-1) + this.fib(num-2);
  }
}

function add(x, y){
  return x + y;
}
